# CI/CD pipeline with comprehensive testing and prompt evaluation
name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov black flake8
    
    - name: Lint code
      run: |
        black --check app/
        flake8 app/ --max-line-length=120
    
    - name: Run unit tests
      run: |
        pytest tests/ -v --cov=app --cov-report=xml
    
    - name: Test prompt evaluation
      run: |
        # NOVEL: Automated prompt effectiveness testing
        python scripts/test_prompts.py --mock-mode
    
    - name: Integration tests
      run: |
        # Start test server
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 5
        
        # Run integration tests
        python scripts/integration_tests.py
    
    - name: Security scan
      run: |
        pip install bandit
        bandit -r app/ -f json -o security-report.json || true
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
